title: "积鱼成水\nGathering Fish Into Water"
author: "Chris Liu"
description: "Usually filled with poetry, short stories and essays. Occasionally (during bad weather) with forgetfulness, happiness and thoughts."
permalink: /:title.html
lang: "en"
date_format: "%B %d, %Y"
url: "https://chris-zy-liu.github.io"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header
excerpt_separator: <!-- excerpt-end -->

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", icon: home}
  - {file: "poetry.md", icon: pen-nib}
  - {file: "essays.md", icon: paperclip}
  - {file: "shortstories.md", icon: quote-left}
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto://chris.zy.liu@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/chris-zy-liu"}
  - {title: Discord, icon: discord, url: "https://discord.gg/Xv8ane3X"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
